### ISSUE TITLE
Exponential and Fibonacci backoffs easily overflow

### ISSUE THREAD

**Issue by magnusbaeck** [sethvargo/go-retry#12]
If you let exponential or Fibonacci backoffs run for a while you'll easily get into an overflow situation. See https://go.dev/play/p/FUNKkZU0Kyn for an example. The [NewExponential documentation](https://github.com/sethvargo/go-retry/blob/v0.2.2/backoff_exponential.go#L23-L24) says

> It's very efficient, but does not check for overflow, so ensure you bound the retry.

but AFAICT you can't prevent overflows with WithCappedDuration since by then the overflow has already happened. How about changing said backoff functions to detect overflows and consistently return the largest time.Duration when the ceiling has been reached? Or am I missing something?

**Comment by sethvargo** [comment]
If you can figure out a way to do that such that it's still safe for concurrent use and doesn't introduce races, I'd be very interested :)

**Comment by sethvargo** [comment]
All the backoffs are safe for concurrent use and need to remain that way. They currently use atomic operations and are incredibly fast. When I benchmarked it, introducing a mutex added a fairly large performance hit.

**Comment by magnusbaeck** [comment]
Percentage-wise I'm sure that's true, but you'd have to run a really tight retry loop for that to have any significance.

I'm not sure what other options there are. It's not entirely easy to make WithCappedDuration to detect overflows (except for the special case of negative durations), and then we're down to adjusting the documentation to be clearer. Right now it's easy to read it as "just use WithCappedDuration and you'll be fine".

**Comment by sethvargo** [comment]
I think `WithCappedDuration`, specifically, can check for negative times and then apply the max.

**Comment by sethvargo** [comment]
The problem is that `Next()` will continue to run, so eventually you'll _stop_ overflowing
