### ISSUE TITLE
DoWithData?

### ISSUE THREAD

**Issue by craigpastro** [sethvargo/go-retry#22]
Hi, me again!

Any thoughts to adding a generic `DoWithData[T](ctx context.Context, b Backoff, f RetryFunc[T]) (T, error) {...}` function similar to https://pkg.go.dev/github.com/cenkalti/backoff/v4#RetryWithData? Obviously, I could use that, but the API here seems more intuitive to me.

Also happy to try a PR if this is something you are interested in.

Thanks!

**Comment by MarcosBustamante** [comment]
Hi @sethvargo can we create a PR in order to add a Do func that implements a return with generics?
