### ISSUE TITLE
Backoff algo and duration

### ISSUE THREAD

**Issue by sheldondz** [sethvargo/go-retry#27]
I need to modify the backoff delay to be a power of 4. 4^0, 4^1...

Is there an easy way to modify this? I would also like to access the duration passed after each retry.

**Comment by sethvargo** [comment]
> I need to modify the backoff delay to be a power of 4. 4^0, 4^1...

```
retry.NewExponential(4 * time.Second)
```

> I would also like to access the duration passed after each retry.

You'd need to make your own backoff or keep track of it outside of a closure. What are you trying to do with the duration?

**Comment by sheldondz** [comment]
> > I need to modify the backoff delay to be a power of 4. 4^0, 4^1...
> 
> ```
> retry.NewExponential(4 * time.Second)
> ```
> The above gives delays of 4s, 8s, 16s, 32s, 64s
> We need delays of 1s, 4s, 16s, 64s
> we implemented out custom backoff as follows
```
exponent := math.Pow(b.base.Seconds(), float64((atomic.AddUint64(&b.attempt, 1) - 1)))
	next := time.Duration(exponent * float64(time.Second))
	if next <= 0 {
		atomic.AddUint64(&b.attempt, ^uint64(0))
		next = math.MaxInt64
	}
	return next, false
```
> > I would also like to access the duration passed after each retry.
> 
> You'd need to make your own backoff or keep track of it outside of a closure. What are you trying to do with the duration?
>> We are using a chatbot and would like to send a warning to the user to wait for x secs.

**Comment by sethvargo** [comment]
Yea for both of those use cases, your best bet is a custom backoff that keeps track of the next duration.
