### ISSUE TITLE
`NewConstant` panics if the given base is zero

### ISSUE THREAD

**Issue by Deleplace** [sethvargo/go-retry#9]
It seems to me that a zero `Backoff` makes sense, from a user POV who would just want to enjoy a retry facility.

Can we make `0` an accepted value for `NewConstant`?

Of course it is not difficult for a user to just call `NewConstant(time.Nanosecond)`, but for flexibility I'm not sure we should advertise "zero delay" as a forbidden parameter.

Zero delays may already occur when using the API, as discussed in #8.

**Comment by sethvargo** [comment]
Hey @Deleplace - I'm really hesitant to do that because it creates a hot loop. The default behavior (without middleware) is to retry indefinitely. Thus `retry.NewConstant(0)` with a non-terminating condition would completely hog all CPU cores until OOM.

**Comment by Deleplace** [comment]
Right, busy loops are not great.

The use cases I had in mind (network requests, DB requests, filesystem I/O) are so slow that they are self-throttled even without a delay between two attempts.

Now I realize that some use cases may indeed hog CPU/memory: whenever a resource is "not ready" and this information is in memory. E.g. "no network for now".

So, a zero backoff delay would be safe only when combined with flavors of `WithMaxRetries`, `WithMaxDuration`, `WithJitter`.

**Comment by sethvargo** [comment]
Even then, I think having a base like 10*time.Nanosecond is a good best practice.
